In [149]:
import pandas as pd

dataset = pd.read_csv("D:/PENS/Semester 4/Data Mining/train.csv")
dataset

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [150]:
test_dataset = pd.read_csv("D:/PENS/Semester 4/Data Mining/titanic_test.csv")
test_dataset

Pclass                                          Name     Sex   Age  \
0         3                              Kelly, Mr. James    male  34.5   
1         3              Wilkes, Mrs. James (Ellen Needs)  female  47.0   
2         2                     Myles, Mr. Thomas Francis    male  62.0   
3         3                              Wirz, Mr. Albert    male  27.0   
4         3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0   
..      ...                                           ...     ...   ...   
413       3                            Spector, Mr. Woolf    male   NaN   
414       1                  Oliva y Ocana, Dona. Fermina  female  39.0   
415       3                  Saether, Mr. Simon Sivertsen    male  38.5   
416       3                           Ware, Mr. Frederick    male   NaN   
417       3                      Peter, Master. Michael J    male   NaN   

     SibSp  Parch              Ticket      Fare Cabin Embarked  
0        0      0              330911    7.8292   NaN        Q  
1        1      0              363272    7.0000   NaN        S  
2        0      0              240276    9.6875   NaN        Q  
3        0      0              315154    8.6625   NaN        S  
4        1      1             3101298   12.2875   NaN        S  
..     ...    ...                 ...       ...   ...      ...  
413      0      0           A.5. 3236    8.0500   NaN        S  
414      0      0            PC 17758  108.9000  C105        C  
415      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416      0      0              359309    8.0500   NaN        S  
417      1      1                2668   22.3583   NaN        C  

[418 rows x 10 columns]

In [151]:
train_data = dataset.loc[:,['Age', 'Fare']]
train_data

Age     Fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

In [152]:
train_data.isnull().sum()

Age     177
Fare      0
dtype: int64

In [153]:
import numpy as np
pos_missing_train1 = np.where(pd.isnull(train_data['Age'])) 
print("posisi atribut Age yang hilang: \n", pos_missing_train1)

posisi atribut Age yang hilang: 
 (array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
        48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
       126, 128, 140, 154, 158, 159, 166, 168, 176, 180, 181, 185, 186,
       196, 198, 201, 214, 223, 229, 235, 240, 241, 250, 256, 260, 264,
       270, 274, 277, 284, 295, 298, 300, 301, 303, 304, 306, 324, 330,
       334, 335, 347, 351, 354, 358, 359, 364, 367, 368, 375, 384, 388,
       409, 410, 411, 413, 415, 420, 425, 428, 431, 444, 451, 454, 457,
       459, 464, 466, 468, 470, 475, 481, 485, 490, 495, 497, 502, 507,
       511, 517, 522, 524, 527, 531, 533, 538, 547, 552, 557, 560, 563,
       564, 568, 573, 578, 584, 589, 593, 596, 598, 601, 602, 611, 612,
       613, 629, 633, 639, 643, 648, 650, 653, 656, 667, 669, 674, 680,
       692, 697, 709, 711, 718, 727, 732, 738, 739, 740, 760, 766, 768,
       773, 776, 778, 783, 790, 792, 793, 815, 825, 826, 828, 832, 837,
       839, 846, 849, 859, 86

In [154]:
#hilangkan missing values
train_data = train_data.dropna()
train_data

Age     Fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
885  39.0  29.1250
886  27.0  13.0000
887  19.0  30.0000
889  26.0  30.0000
890  32.0   7.7500

[714 rows x 2 columns]

In [155]:
train_data.isnull().sum()

Age     0
Fare    0
dtype: int64

In [156]:
test_data = test_dataset.loc[:,['Age', 'Fare']]
test_data

Age      Fare
0    34.5    7.8292
1    47.0    7.0000
2    62.0    9.6875
3    27.0    8.6625
4    22.0   12.2875
..    ...       ...
413   NaN    8.0500
414  39.0  108.9000
415  38.5    7.2500
416   NaN    8.0500
417   NaN   22.3583

[418 rows x 2 columns]

In [157]:
test_data.isnull().sum()

Age     86
Fare     1
dtype: int64

In [158]:
import numpy as np
pos_missing_test1 = np.where(pd.isnull(test_data['Age'])) 
print("posisi atribut Age yang hilang: \n", pos_missing_test1)
print()
pos_missing_test2 = np.where(pd.isnull(test_data['Fare'])) 
print("posisi atribut Fare yang hilang: \n", pos_missing_test2)


posisi atribut Age yang hilang: 
 (array([ 10,  22,  29,  33,  36,  39,  41,  47,  54,  58,  65,  76,  83,
        84,  85,  88,  91,  93, 102, 107, 108, 111, 116, 121, 124, 127,
       132, 133, 146, 148, 151, 160, 163, 168, 170, 173, 183, 188, 191,
       199, 200, 205, 211, 216, 219, 225, 227, 233, 243, 244, 249, 255,
       256, 265, 266, 267, 268, 271, 273, 274, 282, 286, 288, 289, 290,
       292, 297, 301, 304, 312, 332, 339, 342, 344, 357, 358, 365, 366,
       380, 382, 384, 408, 410, 413, 416, 417], dtype=int64),)

posisi atribut Fare yang hilang: 
 (array([152], dtype=int64),)


In [159]:
#hilangkan missing values
test_data = test_data.dropna()
test_data

Age      Fare
0    34.5    7.8292
1    47.0    7.0000
2    62.0    9.6875
3    27.0    8.6625
4    22.0   12.2875
..    ...       ...
409   3.0   13.7750
411  37.0   90.0000
412  28.0    7.7750
414  39.0  108.9000
415  38.5    7.2500

[331 rows x 2 columns]

In [160]:
test_data.isnull().sum()

Age     0
Fare    0
dtype: int64

In [161]:
import numpy as np
import pandas as pd

train_label = []

# Looping untuk menghapus baris-baris yang ada di dalam pos_missing_train1
for index in pos_missing_train1[0]:
    if index in dataset.index:  # Memeriksa apakah index ada dalam indeks dataset
        dataset.drop(index, inplace=True)

# Looping untuk menambahkan nilai 'Survived' ke dalam train_label
for index, row in dataset.iterrows():
    train_label.append(row['Survived'])

# Membuat DataFrame train_label dengan satu kolom 'Survived'
train_label = pd.DataFrame(train_label, columns=['Survived'])

# Cetak train_label_df untuk memeriksa hasilnya
print(train_label)


     Survived
0           0
1           1
2           1
3           1
4           0
..        ...
709         0
710         0
711         1
712         1
713         0

[714 rows x 1 columns]


In [162]:
import numpy as np
import pandas as pd

train_label = []

for index in pos_missing_train1[0]:
    if index in dataset.index:  
        dataset.drop(index, inplace=True)

for index, row in dataset.iterrows():
    train_label.append(row['Survived'])

train_label = pd.DataFrame(train_label, columns=['Survived'])
print(train_label)


     Survived
0           0
1           1
2           1
3           1
4           0
..        ...
709         0
710         0
711         1
712         1
713         0

[714 rows x 1 columns]


In [163]:

titanic_testlabel = pd.read_csv("D:/PENS/Semester 4/Data Mining/titanic_testlabel.csv")
import numpy as np
import pandas as pd

test_label = []

# Looping untuk menghapus baris-baris yang ada di dalam pos_missing_train1
for index in pos_missing_test1[0]:
    if index in titanic_testlabel.index:  # Memeriksa apakah index ada dalam indeks dataset
        titanic_testlabel.drop(index, inplace=True)
        
# Looping untuk menghapus baris-baris yang ada di dalam pos_missing_train1
for index in pos_missing_test2[0]:
    if index in titanic_testlabel.index:  # Memeriksa apakah index ada dalam indeks dataset
        titanic_testlabel.drop(index, inplace=True)

# Looping untuk menambahkan nilai 'Survived' ke dalam train_label
for index, row in titanic_testlabel.iterrows():
    test_label.append(row['Survived'])

# Membuat DataFrame train_label dengan satu kolom 'Survived'
test_label = pd.DataFrame(test_label, columns=['Survived'] )

# Cetak train_label_df untuk memeriksa hasilnya
print(test_label)

     Survived
0           0
1           1
2           0
3           0
4           1
..        ...
326         1
327         1
328         1
329         1
330         0

[331 rows x 1 columns]


In [164]:

titanic_testlabel = pd.read_csv("D:/PENS/Semester 4/Data Mining/titanic_testlabel.csv")

import numpy as np
import pandas as pd

test_label = []

for index in pos_missing_test1[0]:
    if index in titanic_testlabel.index: 
        titanic_testlabel.drop(index, inplace=True)
        
for index in pos_missing_test2[0]:
    if index in titanic_testlabel.index:  
        titanic_testlabel.drop(index, inplace=True)

for index, row in titanic_testlabel.iterrows():
    test_label.append(row['Survived'])

test_label = pd.DataFrame(test_label, columns=['Survived'] )
print(test_label)

     Survived
0           0
1           1
2           0
3           0
4           1
..        ...
326         1
327         1
328         1
329         1
330         0

[331 rows x 1 columns]


In [165]:
#normalisasi pada train_data

#Normalization_ Min-Max 0-1
mindata = train_data.min()
maxdata = train_data.max()
newmin = 0
newmax = 1

train_data= ((train_data-mindata)*(newmax-newmin)/(maxdata-mindata)) + newmin
train_data

Age      Fare
0    0.271174  0.014151
1    0.472229  0.139136
2    0.321438  0.015469
3    0.434531  0.103644
4    0.434531  0.015713
..        ...       ...
885  0.484795  0.056848
886  0.334004  0.025374
887  0.233476  0.058556
889  0.321438  0.058556
890  0.396833  0.015127

[714 rows x 2 columns]

In [166]:
#normalisai pada test data

#Normalization_ Min-Max 0-1
mindata = train_data.min()
maxdata = train_data.max()
newmin = 0
newmax = 1

test_data= ((test_data-mindata)*(newmax-newmin)/(maxdata-mindata)) + newmin
test_data

Age      Fare
0    34.5    7.8292
1    47.0    7.0000
2    62.0    9.6875
3    27.0    8.6625
4    22.0   12.2875
..    ...       ...
409   3.0   13.7750
411  37.0   90.0000
412  28.0    7.7750
414  39.0  108.9000
415  38.5    7.2500

[331 rows x 2 columns]

In [167]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Memisahkan fitur dan label dari data latih dan data uji
X_train = train_data
y_train = train_label
X_test = test_data
y_test = test_label

# Inisialisasi dictionary untuk menyimpan hasil akurasi
class_result = {}

# Melakukan klasifikasi dengan k-NN untuk setiap nilai k dari 1 hingga 10
for k in range(1, 11):
    # Membuat model k-NN
    knn = KNeighborsClassifier(n_neighbors=k)
    
    # Melatih model menggunakan data latih
    knn.fit(X_train, y_train.values.ravel())
    
    # Melakukan prediksi pada data uji
    y_pred = knn.predict(X_test)
    
    # Menghitung akurasi dan menyimpannya dalam dictionary
    accuracy = accuracy_score(y_test, y_pred)
    class_result[f'k={k}'] = accuracy

# Menampilkan hasil akurasi untuk setiap nilai k
for k, accuracy in class_result.items():
    print(f'Accuracy for {k}: {accuracy}')


Accuracy for k=1: 0.4350453172205438
Accuracy for k=2: 0.6163141993957704
Accuracy for k=3: 0.5800604229607251
Accuracy for k=4: 0.5709969788519638
Accuracy for k=5: 0.5770392749244713
Accuracy for k=6: 0.5770392749244713
Accuracy for k=7: 0.5770392749244713
Accuracy for k=8: 0.6042296072507553
Accuracy for k=9: 0.6012084592145015
Accuracy for k=10: 0.6042296072507553


In [168]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

X_train = train_data
y_train = train_label
X_test = test_data
y_test = test_label

class_result = {}

for k in range(1, 11):
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train.values.ravel())
    y_pred = knn.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    
    class_result[f'k={k}'] = accuracy

for k, accuracy in class_result.items():
    print(f'Accuracy for {k}: {accuracy}')


Accuracy for k=1: 0.4350453172205438
Accuracy for k=2: 0.6163141993957704
Accuracy for k=3: 0.5800604229607251
Accuracy for k=4: 0.5709969788519638
Accuracy for k=5: 0.5770392749244713
Accuracy for k=6: 0.5770392749244713
Accuracy for k=7: 0.5770392749244713
Accuracy for k=8: 0.6042296072507553
Accuracy for k=9: 0.6012084592145015
Accuracy for k=10: 0.6042296072507553
